meta:
  task: AttnGAN-1
  checkpoint_path: "/home/c7w/landscape/checkpoints/" # Would save checkpoints to `<checkpoint_path>/<task>/`
  test_save_path: "/home/c7w/landscape/test_save/" # Would save test images to `<test_save_path>/<task>/`
  log_path: "/home/c7w/landscape/logs/" # Would save logs to `<log_path>/<task>/`
  load: # Checkpoint ID to be loaded, if None not load
  seed: # Seed

train:
  max_epochs: 1000
  max_iterations: 1000000
  batch_size: 16
  save_every_iteration: 1000

generator:
  type: UNet
  optimizer:
    type: Adam
    lr: 0.0001
    beta1: 0.9
    beta2: 0.999
    clip_grad_norm: 1000.0
    clip_weights: 10.0

discriminator:
  type: CNN
  optimizer:
      type: Adam
      lr: 0.0001
      beta1: 0.9
      beta2: 0.99
