meta:
  task: baseline
  checkpoint_path: "/home/c7w/landscape/checkpoints/" # Would save checkpoints to `<checkpoint_path>/<task>/`
  test_save_path: "/home/c7w/landscape/test_save/" # Would save test images to `<test_save_path>/<task>/`
  log_path: "/home/c7w/landscape/logs/" # Would save logs to `<log_path>/<task>/`
  log_interval: 2
  load: # Checkpoint ID to be loaded, if None not load
  seed: 123123 # Seed


training:
  max_epochs: 1000
  max_iterations: 1000000
  batch_size: 32
  save_every_iteration: -1 # Save every n iterations, -1 for disabled
  save_every_epoch: 10 # Save every n epochs, -1 for disabled
  step_every_iteration: 1 # Step every n iterations

network:
  generator:
    type: UNet
    optimizer:
      type: Adam
      lr: 0.0002
      beta1: 0.9
      beta2: 0.999
      weight_decay: 0.0

  discriminator:
    type: CNN
    optimizer:
        type: Adam
        lr: 0.0002
        beta1: 0.9
        beta2: 0.99
        weight_decay: 0.0

loss:
  generator:
    - type: 'l1'
      weight: 100.0
    - type: "bce"
      weight: 1.0
  discriminator:
    - type: "bce"
      weight: 0.5
